        </main>
        <footer>
            <p>A project from <strong><a href="http://teamtreehouse.com">Treehouse</a></strong></p>
            <nav>
                <a href="/" class="<?=$routeName === 'home'?'selected':'unselected';?>">About</a>
                <a href="/contact" class="<?=$routeName === 'contact'?'selected':'unselected';?>">Contact</a>
            </nav>
        </footer>
    </body>
</html>
