<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Ralph Waldo Emerson</title>
        <meta charset="utf-8">
        <meta name="description" content="Ralph Waldo Emerson">
        <meta name="author" content="Treehouse">
        <link href='//fonts.googleapis.com/css?family=Roboto:400,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="css/master.css">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="js/global.js"></script>
    </head>
    <body>
        <!--
        <div id="feedback" class="success">
        <h3>Success!</h3>
        <p>You're reading all about Emerson.</p>
        </div>
        -->
        <header>
            <h1>Ralph Waldo Emerson</h1>
            <nav>
                <a href="/" class="<?=$routeName === 'home'?'selected':'unselected';?>">About</a>
                <a href="/contact" class="<?=$routeName === 'contact'?'selected':'unselected';?>">Contact</a>
            </nav>
        </header>
        <div class="emerson">
            <img src="images/emerson.jpg" alt="Picture of Ralph Waldo Emerson">
        </div>
        <main>
